### ISSUE TITLE
Landscape format

### ISSUE THREAD

**Issue by elmeerr** [hearsid/ng-html-to-pdf-save#25]
Hi,

I'm using this directive and it works properly, however my layout is to print as landscape. There is a property do make the PDF landscape?

Kind regards.

**Comment by Slowair6** [comment]
Have you find a solution yet? I'm looking for a way to resize the paper which is similar thing.

the question is how to config the directive

**Comment by elmeerr** [comment]
@Slowair6 I didn't look at anymore...I was trying to find another solution in the meantime. I'll also see the directive to try to implement the landscape option

**Comment by kmilovm** [comment]
You just have to play around with jsPDF and its initialization parameters, in this case you should look for jsPDF object creation and replace with the one that you want, ie:  new jsPDF('l', 'pt', 'legal'); that works for me. 
If you want to look at deeper on those parameters you should look at here: http://rawgit.com/MrRio/jsPDF/master/docs/index.html

I strongly recommend you download the debug versions of the js for making that adjustments.

Hope that it helps, because this great lib seems to be alone on the web....

**Comment by hearsid** [comment]
Sorry for the late reply, I agree with @kmilovm

**Comment by elmeerr** [comment]
This issue can be closed
